### ISSUE TITLE
Always "Failed to Download"

### ISSUE THREAD

**Issue by rkuli** [glomatico/gamdl#101]
<img width="825" alt="Screenshot 2024-04-12 at 9 27 53 AM" src="https://github.com/glomatico/gamdl/assets/126831718/fcdba69b-049a-4634-82f4-dd838c0f20e9">
<img width="323" alt="Screenshot 2024-04-12 at 9 31 44 AM" src="https://github.com/glomatico/gamdl/assets/126831718/abbfaefb-c6ec-462c-8725-1aad37891639">
<img width="767" alt="Screenshot 2024-04-12 at 9 32 57 AM" src="https://github.com/glomatico/gamdl/assets/126831718/85c1b2f8-c453-4876-b603-1a4c39b78603">
I have ffmpeg as well as mp4decrypt in my paths, i have the cookies.txt file in the same directory, and i've tried changing the song codec several times but it never downloads, what am i missing?

**Comment by glomatico** [comment]
Please end the output of the same command but with `--print-exceptions`

**Comment by rkuli** [comment]
Alright, this seemed to change, I got this:
[INFO     10:01:52] (Track 1/1 from URL 1/1) Downloading "Ain't It Fun"
[ERROR    10:01:52] (Track 1/1 from URL 1/1) Failed to download "Ain't It Fun"
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 1344, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1336, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1382, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1091, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1035, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1477, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 1042, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 1320, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/gamdl/cli.py", line 498, in main
    stream_info = downloader_song_legacy.get_stream_info(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/gamdl/downloader_song_legacy.py", line 24, in get_stream_info
    m3u8_obj = m3u8.load(stream_info.stream_url)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/m3u8/__init__.py", line 94, in load
    content, base_uri = http_client.download(uri, timeout, headers, verify_ssl)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/m3u8/httpclient.py", line 16, in download
    resource = opener.open(uri, timeout=timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 515, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 532, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 1392, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/request.py", line 1347, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)>
[INFO     10:01:52] Done (1 error(s))

**Comment by rkuli** [comment]
Is this with the cookies.txt thing or something else entirely?

**Comment by rkuli** [comment]
Never mind, I fixed it

**Comment by rkuli** [comment]
Thank you for your help

**Comment by eitopomar** [comment]
How did you fix it?

**Comment by glomatico** [comment]
> How did you fix it?

See https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify

**Comment by eitopomar** [comment]
> > How did you fix it?
> 
> See https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify

Awesome. That did it.

```bash
open /Applications/Python\ 3.12/Install\ Certificates.command
```
