### ISSUE TITLE
widevine license issue when selecting ALAC

### ISSUE THREAD

**Issue by rkuli** [glomatico/gamdl#102]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/gamdl/apple_music_api.py", line 232, in get_widevine_license
    assert widevine_license
           ^^^^^^^^^^^^^^^^
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/gamdl/cli.py", line 514, in main
    decryption_key = downloader.get_decryption_key(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/gamdl/downloader.py", line 169, in get_decryption_key
    license = self.apple_music_api.get_widevine_license(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/gamdl/apple_music_api.py", line 238, in get_widevine_license
    self._raise_response_exception(response)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/gamdl/apple_music_api.py", line 72, in _raise_response_exception
    raise Exception(
Exception: Request failed with status code 200: {"status":-1002}

**Comment by rkuli** [comment]
Also, whenever you update gamdl, what is the command for updating this since i used pip3 install?

**Comment by glomatico** [comment]
As the readme says, support for non-legacy codecs are not guaranteed, as most of the songs cannot be downloaded when using non-legacy codecs.
