### ISSUE TITLE
i didnt able to run it gives error

### ISSUE THREAD

**Issue by jimmyra62** [glomatico/gamdl#117]
C:\Users\berki>gamdl https://music.apple.com/tr/album/neon-pill/1733061411
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\berki\AppData\Local\Programs\Python\Python311\Scripts\gamdl.exe\__main__.py", line 7, in <module>
  File "C:\Users\berki\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\berki\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1077, in main
    with self.make_context(prog_name, args, **extra) as ctx:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\berki\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 943, in make_context
    self.parse_args(ctx, args)
  File "C:\Users\berki\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1408, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\berki\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 2400, in handle_parse_result
    value = self.process_value(ctx, value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\berki\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 2362, in process_value
    value = self.callback(ctx, self, value)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\berki\AppData\Local\Programs\Python\Python311\Lib\site-packages\gamdl\cli.py", line 57, in load_config_file
    config_file = dict(json.loads(ctx.params["config_path"].read_text()))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\berki\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\berki\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\berki\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 35 column 5 (char 1143)

**Comment by glomatico** [comment]
You messed with your configuration file. Try deleting it and run the program again.

**Comment by jimmyra62** [comment]
Can you explain in detail. i am not good at python, what is configuration file
thank you

**Comment by glomatico** [comment]
Run this command:
```bash
del %userprofile%\.gamdl\config.json
```
And try running gamdl again.

**Comment by jimmyra62** [comment]
C:\Users\berki>gamdl https://music.apple.com/tr/album/shut-up-and-dance/1743321878?i=1743321885
[CRITICAL 06:52:28] Cookies file not found at "cookies.txt"

after run the command , I ran gamdl and it gives the error above, I had your instructions before and I didn't know where will I put cookies.txt, I think all problems coming from this

**Comment by glomatico** [comment]
Try opening your terminal and run this command
```
explorer .
```
Then move the cookies file to the folder that opened and try using gamdl again.

**Comment by jimmyra62** [comment]
now it gives this error. I downloaded ffmpeg files from your instructions link and install it.

C:\Users\berki>gamdl https://music.apple.com/tr/album/hang-on/1733581722?i=1733582432
[CRITICAL 20:35:40] ffmpeg not found at "ffmpeg"

**Comment by glomatico** [comment]
> Try opening your terminal and run this command
> 
> ```
> explorer .
> ```
> 
> Then move the cookies file to the folder that opened and try using gamdl again.

Do the same thing as here but with the ffmpeg.exe file.

**Comment by jimmyra62** [comment]
Now it is working , thank you very much. I wish the people who created qobuz dl were patient like you and help me but they are not.

**Comment by jimmyra62** [comment]
one more question , the files downloading as regular aac even I choose the spatial audio song,  what will I do for Spatial AAC/Dolby Atmos/ALAC

**Comment by glomatico** [comment]
> one more question , the files downloading as regular aac even I choose the spatial audio song, what will I do for Spatial AAC/Dolby Atmos/ALAC

Sorry, I didn't understand your question

**Comment by jimmyra62** [comment]
How will I download as ALAC or spatial audio. All downloads coming as regular 256 kbps m4a

**Comment by glomatico** [comment]
Instructions aew on the README
