### ISSUE TITLE
Error while download

### ISSUE THREAD

**Issue by PogusTheWhisper** [glomatico/gamdl#130]
Traceback (most recent call last):
  File "C:\Users\pogus-asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\gamdl\cli.py", line 466, in main
    f'({queue_progress}) Downloading "{track["attributes"]["name"]}"'
                                       ~~~~~^^^^^^^^^^^^^^
KeyError: 'attributes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\pogus-asus\AppData\Local\Programs\Python\Python312\Scripts\gamdl.exe\__main__.py", line 7, in <module>
  File "C:\Users\pogus-asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pogus-asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\pogus-asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pogus-asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pogus-asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\gamdl\cli.py", line 716, in main
    f'({queue_progress}) Failed to download "{track["attributes"]["name"]}"',
                                              ~~~~~^^^^^^^^^^^^^^
KeyError: 'attributes'

**Comment by glomatico** [comment]
Which URL did you tried?

**Comment by PogusTheWhisper** [comment]
Now I got this
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\pogus-asus\AppData\Local\Programs\Python\Python312\Scripts\gamdl.exe\__main__.py", line 7, in <module>
  File "C:\Users\pogus-asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pogus-asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\pogus-asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pogus-asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pogus-asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\gamdl\cli.py", line 726, in main
    downloader.cleanup_temp_path()
  File "C:\Users\pogus-asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\gamdl\downloader.py", line 464, in cleanup_temp_path
    shutil.rmtree(self.temp_path)
  File "C:\Users\pogus-asus\AppData\Local\Programs\Python\Python312\Lib\shutil.py", line 781, in rmtree
    return _rmtree_unsafe(path, onexc)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pogus-asus\AppData\Local\Programs\Python\Python312\Lib\shutil.py", line 635, in _rmtree_unsafe
    onexc(os.unlink, fullname, err)
  File "C:\Users\pogus-asus\AppData\Local\Programs\Python\Python312\Lib\shutil.py", line 633, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'temp\\80007866_remuxed.m4a'

**Comment by PogusTheWhisper** [comment]
My playlist : https://music.apple.com/th/playlist/suki-backup/pl.u-zPyLZxRtejkgaMg
