### ISSUE TITLE
No module named 'gamdl.storefront_ids

### ISSUE THREAD

**Issue by evafans** [glomatico/gamdl#14]
13957
Traceback (most recent call last):
  File "C:\Users\Administrator\gamdl\gamdl.py", line 10, in <module>
    import gamdl.storefront_ids
  File "C:\Users\Administrator\gamdl\gamdl.py", line 10, in <module>
    import gamdl.storefront_ids
ModuleNotFoundError: No module named 'gamdl.storefront_ids'; 'gamdl' is not a package

I've reinstall it, this is new, never happened in the last commit

**Comment by evafans** [comment]
I don't know where to put my keys either.
