### ISSUE TITLE
KeyError: 'curatorName'

### ISSUE THREAD

**Issue by whairdo** [glomatico/gamdl#152]
C:\F>gamdl "https://music.apple.com/cn/playlist/pl.626ebb23f2914698bf4804904951199c"
[INFO     21:36:12] Starting Gamdl
[WARNING  21:36:14] mp4decrypt not found at "mp4decrypt", music videos will not be downloaded
[INFO     21:36:14] (URL 1/1) Checking "https://music.apple.com/cn/playlist/pl.626ebb23f2914698bf4804904951199c"
[INFO     21:36:15] (Track 1/28 from URL 1/1) Downloading "Killer-Tune"
[ERROR    21:36:16] (Track 1/28 from URL 1/1) Failed to download "Killer-Tune"
Traceback (most recent call last):
  File "C:\Users\kishoka\AppData\Roaming\Python\Python312\site-packages\gamdl\cli.py", line 516, in main
    **downloader.get_playlist_tags(
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kishoka\AppData\Roaming\Python\Python312\site-packages\gamdl\downloader.py", line 258, in get_playlist_tags
    "playlist_artist": playlist_attributes["curatorName"],
                       ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'curatorName'

C:\F>gamdl "https://music.apple.com/cn/playlist/ikimonogakari-next-steps/pl.ac22e9e4574443478094361a62bc428a"
[INFO     21:48:23] Starting Gamdl
[WARNING  21:48:25] mp4decrypt not found at "mp4decrypt", music videos will not be downloaded
[INFO     21:48:25] (URL 1/1) Checking "https://music.apple.com/cn/playlist/ikimonogakari-next-steps/pl.ac22e9e4574443478094361a62bc428a"
[INFO     21:48:30] (Track 1/15 from URL 1/1) Downloading "message"
[ERROR    21:48:33] (Track 1/15 from URL 1/1) Failed to download "message"
Traceback (most recent call last):
  File "C:\Users\kishoka\AppData\Roaming\Python\Python312\site-packages\gamdl\cli.py", line 516, in main
    **downloader.get_playlist_tags(
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kishoka\AppData\Roaming\Python\Python312\site-packages\gamdl\downloader.py", line 258, in get_playlist_tags
    "playlist_artist": playlist_attributes["curatorName"],
                       ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'curatorName'

![image](https://github.com/user-attachments/assets/7e686f39-898d-4f0f-8754-3d02f42bb1e0)
![image](https://github.com/user-attachments/assets/81f16048-b1d1-4f2d-a41d-d92cd7f1110b)

As is shown in the pictures, the curator info is somehow lost in the Chinese verison of the playlist.

**Comment by glomatico** [comment]
Should be fixed on the latest version.
