### ISSUE TITLE
Getting an error for a video

### ISSUE THREAD

**Issue by wiseguy100** [glomatico/gamdl#157]
[INFO     05:29:47] Starting Gamdl
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Scripts\gamdl.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\gamdl\cli.py", line 361, in main
    apple_music_api = AppleMusicApi(
                      ^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\gamdl\apple_music_api.py", line 31, in __init__
    self._set_session()
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\gamdl\apple_music_api.py", line 63, in _set_session
    ).group(1)
      ^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by glomatico** [comment]
Mind sharing which link you are using?

**Comment by wiseguy100** [comment]
https://music.apple.com/us/music-video/jai-ho-you-are-my-destiny/1467926843

**Comment by mattneub** [comment]
I'm having this problem too, I can't download any music because of this same AttributeError.

```
Traceback (most recent call last):
  File "/Users/mattm1/Library/Python/3.9/bin/gamdl", line 8, in <module>
    sys.exit(main())
  File "/Users/mattm1/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mattm1/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
  File "/Users/mattm1/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mattm1/Library/Python/3.9/lib/python/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
  File "/Users/mattm1/Library/Python/3.9/lib/python/site-packages/gamdl/cli.py", line 362, in main
    apple_music_api = AppleMusicApi(
  File "/Users/mattm1/Library/Python/3.9/lib/python/site-packages/gamdl/apple_music_api.py", line 33, in __init__
    self._set_session()
  File "/Users/mattm1/Library/Python/3.9/lib/python/site-packages/gamdl/apple_music_api.py", line 68, in _set_session
    index_js_uri = re.search(
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by glomatico** [comment]
> I'm having this problem too, I can't download any music because of this same AttributeError.
> 
> ```
> Traceback (most recent call last):
>   File "/Users/mattm1/Library/Python/3.9/bin/gamdl", line 8, in <module>
>     sys.exit(main())
>   File "/Users/mattm1/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1161, in __call__
>     return self.main(*args, **kwargs)
>   File "/Users/mattm1/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1082, in main
>     rv = self.invoke(ctx)
>   File "/Users/mattm1/Library/Python/3.9/lib/python/site-packages/click/core.py", line 1443, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/Users/mattm1/Library/Python/3.9/lib/python/site-packages/click/core.py", line 788, in invoke
>     return __callback(*args, **kwargs)
>   File "/Users/mattm1/Library/Python/3.9/lib/python/site-packages/gamdl/cli.py", line 362, in main
>     apple_music_api = AppleMusicApi(
>   File "/Users/mattm1/Library/Python/3.9/lib/python/site-packages/gamdl/apple_music_api.py", line 33, in __init__
>     self._set_session()
>   File "/Users/mattm1/Library/Python/3.9/lib/python/site-packages/gamdl/apple_music_api.py", line 68, in _set_session
>     index_js_uri = re.search(
> AttributeError: 'NoneType' object has no attribute 'group'
> ```

you're using a very old version

**Comment by mattneub** [comment]
Sorry, old version of what? Just installed gamdl for first time just now.

**Comment by glomatico** [comment]
> Sorry, old version of what? Just installed gamdl for first time just now.

of gamdl. you need to update it. also update your python version, 3.9 isnt supported. need at least 3.10+.

**Comment by mattneub** [comment]
Nailed it, thanks. You might want to mention in the instructions that you can just say `brew install gamdl` on Mac. Thank you for the tool and the help! 👍
