### ISSUE TITLE
I have put the wvd file in the directory. Or prompt an error?

### ISSUE THREAD

**Issue by steamgirl2020** [glomatico/gamdl#17]
I have put the wvd file in the directory. Or prompt an error?
please help，thx

Traceback (most recent call last):
  File "C:\Python398\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python398\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python398\Scripts\gamdl.exe\__main__.py", line 7, in <module>
  File "C:\Python398\lib\site-packages\gamdl\__init__.py", line 101, in main
    dl = Gamdl(
  File "C:\Python398\lib\site-packages\gamdl\gamdl.py", line 32, in __init__
    raise Exception('.wvd file not found')
Exception: .wvd file not found

**Comment by glomatico** [comment]
You don't seem to be running gamdl on the same directory where the .wvd is.
