### ISSUE TITLE
module error

### ISSUE THREAD

**Issue by timoramuzat** [glomatico/gamdl#23]
C:\Users\timo\Downloads\gamdl-main\gamdl-main>python gamdl https://music.apple.com/us/album/endless-summer-vacation/1663973555
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\timo\Downloads\gamdl-main\gamdl-main\gamdl\__main__.py", line 1, in <module>
    import gamdl
  File "C:\Users\timo\Downloads\gamdl-main\gamdl-main\gamdl\gamdl.py", line 11, in <module>
    import gamdl.storefront_ids
ModuleNotFoundError: No module named 'gamdl.storefront_ids'; 'gamdl' is not a package

**Comment by glomatico** [comment]
You have to install gamdl with pip
`pip install gamdl`
And then use `gamdl https://music.apple.com/us/album/endless-summer-vacation/1663973555`

You can also run as a module
`pip install requirements.txt`
`python -m gamdl`
