### ISSUE TITLE
mp4decrypt not on path..

### ISSUE THREAD

**Issue by timoramuzat** [glomatico/gamdl#24]
gamdl
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\timo\AppData\Local\Programs\Python\Python311\Scripts\gamdl.exe\__main__.py", line 7, in <module>
  File "C:\Users\timo\AppData\Local\Programs\Python\Python311\Lib\site-packages\gamdl\__init__.py", line 11, in main
    raise Exception('mp4decrypt is not on PATH')
Exception: mp4decrypt is not on PATH

**Comment by glomatico** [comment]
Refer to https://stackoverflow.com/a/64233155
