### ISSUE TITLE
Failed to download v2

### ISSUE THREAD

**Issue by a1waysbeta** [glomatico/gamdl#27]
I subscribed to apple music, and re-exported cookies, but the download was difficult to succeed, and an error was thrown at any time. Is there anything else that needs special attention? Sometimes I can see the download reaches 100%, and then it prompts that the download failed.

PS D:\Portable Soft\Downloads> gamdl https://music.apple.com/cn/album/%E9%9A%BE%E5%BF%B5%E7%9A%84%E7%BB%8F/1072048491?i=1072048505
Downloading "难念的经" (track 1/1 from URL 1/1)
[download] Got error: <urlopen error EOF occurred in violation of protocol (_ssl.c:992)>
[download] Got error: <urlopen error EOF occurred in violation of protocol (_ssl.c:992)>
[download] 86.7% of ~ 9.53MiB at 264.14KiB/s ETA 00:09 (frag 26/30)
Failed to download "难念的经" (track 1/1 from URL 1/1)
Done (1 error(s))

PS D:\Portable Soft\Downloads> gamdl https://music.apple.com/cn/album/%E9%9A%BE%E5%BF%B5%E7%9A%84%E7%BB%8F/1072048491?i=1072048505
Downloading "难念的经" (track 1/1 from URL 1/1)
ERROR: [generic] None: Unable to download webpage: The read operation timed out (caused by TimeoutError('The read operation timed out')); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriateissue template. Confirm you are on the latest version using  yt-dlp -U
Failed to download "难念的经" (track 1/1 from URL 1/1)
Done (1 error(s))
PS D:\Portable Soft\Downloads> gamdl https://music.apple.com/cn/album/%E9%9A%BE%E5%BF%B5%E7%9A%84%E7%BB%8F/1072048491?i=1072048505
Downloading "难念的经" (track 1/1 from URL 1/1)
Failed to download "难念的经" (track 1/1 from URL 1/1)
Done (1 error(s))
PS D:\Portable Soft\Downloads> gamdl https://music.apple.com/us/album/%E8%8A%B1%E5%BF%83/151290612?uo=4
Traceback (most recent call last):
  File "C:\Users\alway\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\alway\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "C:\Users\alway\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
                ^^^^^^^^^^^^^^^^
  File "C:\Users\alway\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alway\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alway\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alway\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1075, in _create
    self.do_handshake()
  File "C:\Users\alway\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:992)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\alway\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\alway\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\alway\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='beta.music.apple.com', port=443): Max retries exceeded withurl: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:992)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\alway\AppData\Local\Programs\Python\Python311\Scripts\gamdl.exe\__main__.py", line 7, in <module>
  File "C:\Users\alway\AppData\Local\Programs\Python\Python311\Lib\site-packages\gamdl\__init__.py", line 107, in main
    dl = Gamdl(
         ^^^^^^
  File "C:\Users\alway\AppData\Local\Programs\Python\Python311\Lib\site-packages\gamdl\gamdl.py", line 52, in __init__
    web_page = self.session.get('https://beta.music.apple.com').text
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alway\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alway\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alway\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alway\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='beta.music.apple.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:992)')))
PS D:\Portable Soft\Downloads> gamdl https://music.apple.com/cn/album/%E9%9A%BE%E5%BF%B5%E7%9A%84%E7%BB%8F/1072048491?i=1072048505
Downloading "难念的经" (track 1/1 from URL 1/1)
Failed to download "难念的经" (track 1/1 from URL 1/1)
Done (1 error(s))
PS D:\Portable Soft\Downloads> gamdl https://music.apple.com/cn/album/%E6%9C%89%E6%B2%A1%E6%9C%89%E4%B8%80%E9%A6%96%E6%AD%8C%E4%BC%9A%E8%AE%A9%E4%BD%A0%E6%83%B3%E8%B5%B7%E6%88%91/151212454?i=151212668
Downloading "有没有一首歌会让你想起我" (track 1/1 from URL 1/1)
Failed to download "有没有一首歌会让你想起我" (track 1/1 from URL 1/1)
Done (1 error(s))

**Comment by glomatico** [comment]
Try adding aria2c to PATH.

**Comment by a1waysbeta** [comment]
The three exe files aria2c, MP4Box and mp4decrypt are in one folder and have been added to path.
