### ISSUE TITLE
Failed to download in google colab

### ISSUE THREAD

**Issue by geoplayx** [glomatico/gamdl#28]
It's downloading in progress but fails when it is finished. -t and -f doesn't work. please help. Thanks!

**Comment by glomatico** [comment]
Please provide output with `-e`

**Comment by geoplayx** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gamdl/__init__.py", line 170, in main
    dl.decrypt(encrypted_location, decrypted_location, decryption_keys)
  File "/usr/local/lib/python3.9/dist-packages/gamdl/gamdl.py", line 183, in decrypt
    subprocess.run(
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: 'mp4decrypt'
Done (1 error(s))

**Comment by glomatico** [comment]
Redo step 3 on readme.
