### ISSUE TITLE
failed to download

### ISSUE THREAD

**Issue by TszhoKong** [glomatico/gamdl#29]
could you please help? i have trouble downloading music.

PS C:\Users\Tszho Kong\Desktop\Apple Music\gamdl-1.9> gamdl https://music.apple.com/tr/album/up-in-flames/1440818807?i=1440818813
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Tszho Kong\AppData\Local\Programs\Python\Python311\Scripts\gamdl.exe\__main__.py", line 7, in <module>
  File "C:\Users\Tszho Kong\AppData\Local\Programs\Python\Python311\Lib\site-packages\gamdl\__init__.py", line 113, in main
    dl = Gamdl(
         ^^^^^^
  File "C:\Users\Tszho Kong\AppData\Local\Programs\Python\Python311\Lib\site-packages\gamdl\gamdl.py", line 59, in __init__
    index_js_uri = re.search('(?<=index\.)(.*?)(?=\.js")', web_page).group(1)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by glomatico** [comment]
Fixed on version 1.9
