### ISSUE TITLE
TypeError: argument of type 'WindowsPath' is not iterable

### ISSUE THREAD

**Issue by balleno75** [glomatico/gamdl#32]
Hello,

Thank you very much for the application. I have followed the steps for its installation and configuration, but this error is generated when I try to download any content (song, album, etc.)

gamdl https://music.apple.com/es/album/suburbia-remastered/709434153?i=709434468 -e -t C:\Users\Manu\Downloads\temp -f C:\Users\Manu\Downloads\AppleMusic
Downloading "Suburbia (Remastered)" (track 1/1 from URL 1/1)
Failed to download "Suburbia (Remastered)" (track 1/1 from URL 1/1)
Traceback (most recent call last):
  File "c:\users\manu\appdata\local\programs\python\python37\lib\site-packages\gamdl\__init__.py", line 171, in main
    dl.decrypt(encrypted_location, decrypted_location, decryption_keys)
  File "c:\users\manu\appdata\local\programs\python\python37\lib\site-packages\gamdl\gamdl.py", line 190, in decrypt
    check=True
  File "c:\users\manu\appdata\local\programs\python\python37\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\users\manu\appdata\local\programs\python\python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "c:\users\manu\appdata\local\programs\python\python37\lib\subprocess.py", line 1148, in _execute_child
    args = list2cmdline(args)
  File "c:\users\manu\appdata\local\programs\python\python37\lib\subprocess.py", line 555, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'WindowsPath' is not iterable
Done (1 error(s))

You can help me?. Thank you so much. A greeting.

**Comment by Fadexz** [comment]
Getting the same error, used to work for me but I did try installing it again...
