### ISSUE TITLE
Exception: .wvd file not found

### ISSUE THREAD

**Issue by gmankab** [glomatico/gamdl#34]
```txt
➜ python -m gamdl http://music.apple.com/ru/playlist/pl.u-55D6ZNlH6M8Y2AD
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/gmanka/Documents/.venv/lib/python3.11/site-packages/gamdl/__main__.py", line 4, in <module>
    main()
  File "/home/gmanka/Documents/.venv/lib/python3.11/site-packages/gamdl/__init__.py", line 102, in main
    dl = Gamdl(
         ^^^^^^
  File "/home/gmanka/Documents/.venv/lib/python3.11/site-packages/gamdl/gamdl.py", line 42, in __init__
    raise Exception(".wvd file not found")
Exception: .wvd file not found
```
i runned it in arch distrobox

**Comment by gmankab** [comment]
sorry i should have read the manual first
