### ISSUE TITLE
No module named 'gamdl.storefront_ids

### ISSUE THREAD

**Issue by BoyCanad** [glomatico/gamdl#36]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Admin\Downloads\gamdl-1.9.1\gamdl-1.9.1\gamdl\__main__.py", line 1, in <module>
    import gamdl
  File "C:\Users\Admin\Downloads\gamdl-1.9.1\gamdl-1.9.1\gamdl\gamdl.py", line 11, in <module>
    import gamdl.storefront_ids
ModuleNotFoundError: No module named 'gamdl.storefront_ids'; 'gamdl' is not a package

I'm new and having this problem

**Comment by glomatico** [comment]
Run with python -m gamdl (the folder)

**Comment by BoyCanad** [comment]
it's says a new error
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Admin\AppData\Roaming\Python\Python311\site-packages\gamdl\__main__.py", line 4, in <module>
    main()
  File "C:\Users\Admin\AppData\Roaming\Python\Python311\site-packages\gamdl\__init__.py", line 13, in main
    raise Exception(f"{tool} is not on PATH")
Exception: MP4Box is not on PATH

but MP4Box is on my PATH.

**Comment by BoyCanad** [comment]
Do i need to path the exe file or the directory
