### ISSUE TITLE
.wvd file not found at "device.wvd"

### ISSUE THREAD

**Issue by toughguystudios** [glomatico/gamdl#69]
UPDATE: I downgraded (I believe) my version of protobuf and this is the response I am now getting:

Traceback (most recent call last):
File "/Users/dumper-main/dump_keys.py", line 14, in
device = frida.get_usb_device()
^^^^^^^^^^^^^^^^^^^^^^
File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/frida/init.py", line 137, in get_usb_device
return get_device_manager().get_usb_device(timeout)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/frida/core.py", line 1178, in get_usb_device
return self.get_device_matching(lambda d: d.type == "usb", timeout)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/frida/core.py", line 86, in wrapper
return f(*args, **kwargs)
^^^^^^^^^^^^^^^^^^
File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/frida/core.py", line 1201, in get_device_matching
return Device(self._impl.get_device_matching(lambda d: predicate(Device(d)), raw_timeout))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frida.InvalidArgumentError: device not found

I had trouble with "cookies.txt" missing, then ffmpeg missing (because of permissions) but now I'm getting .wvd file not found at "device.wvd".
   I'm using a macbook, I don't have any android devices. Is there a work around? I also read somewhere that as of May 2021, Google patched the Widevine decryptor, does that mean this isn't possible anymore?

also when I tried to use Dumper with mac terminal, I received the following response:

Hi, I ran the script and received the following response, Can you tell me what it means/what went wrong and how to resolve, Thanks:

Ryans-MBP:dumper-main python3 dump_keys.py
Traceback (most recent call last):
  File "/Users/dumper-main/dump_keys.py", line 6, in <module>
    from Helpers.Scanner import Scan
  File "/Users/dumper-main/Helpers/Scanner.py", line 7, in <module>
    from Helpers.wv_proto2_pb2 import SignedLicenseRequest
  File "/Users/dumper-main/Helpers/wv_proto2_pb2.py", line 33, in <module>
    _descriptor.EnumValueDescriptor(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/google/protobuf/descriptor.py", line 789, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

**Comment by florisdipt** [comment]
It seems you meant to make an issue on the https://github.com/wvdumper/dumper repository, protobuf is not a dependency of this project.
