### ISSUE TITLE
Error while running. 

### ISSUE THREAD

**Issue by Some1Rxndom** [glomatico/gamdl#78]
Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\gamdl.exe\__main__.py", line 7, in <module>
  File "c:\python39\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "c:\python39\lib\site-packages\click\core.py", line 1077, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "c:\python39\lib\site-packages\click\core.py", line 943, in make_context
    self.parse_args(ctx, args)
  File "c:\python39\lib\site-packages\click\core.py", line 1408, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "c:\python39\lib\site-packages\click\core.py", line 2400, in handle_parse_result
    value = self.process_value(ctx, value)
  File "c:\python39\lib\site-packages\click\core.py", line 2362, in process_value
    value = self.callback(ctx, self, value)
  File "c:\python39\lib\site-packages\gamdl\cli.py", line 33, in no_config_callback
    config_file = dict(json.load(f))
  File "c:\python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "c:\python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "c:\python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\python39\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid \escape: line 2 column 22 (char 23)

**Comment by cakroqi223** [comment]
how to fix this issue: [CRITICAL 12:04:30] Cookies file not found at "cookies.txt"
