### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by cx410** [glomatico/gamdl#92]
What is the solution?

>C:\Users\Administrator>gamdl "https://music.apple.com/us/album/never-gonna-give-you-up-2022-remaster/1626265761?i=1626265765"
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\Scripts\gamdl.exe\__main__.py", line 4, in <module>
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\gamdl\cli.py", line 17, in <module>
    from .downloader_song import DownloaderSong
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\gamdl\downloader_song.py", line 20, in <module>
    class DownloaderSong:
  File "c:\users\administrator\appdata\local\programs\python\python39\lib\site-packages\gamdl\downloader_song.py", line 57, in DownloaderSong
    def get_playlist_from_codec(self, m3u8_data: dict) -> dict | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by glomatico** [comment]
what is ur python version?

**Comment by cx410** [comment]
python --version
Python 3.9.1

**Comment by glomatico** [comment]
should be fixed on the new version
